#!/usr/bin/env bash
# Generate a .env for Docker Compose with host UID/GID and project variables.
# Interactive behavior: if .env exists, warn and prompt to confirm overwrite; otherwise create a new one.
# Usage:
#   ./gen-dotenv.sh                 # use current user's ids
#   ./gen-dotenv.sh --from-dir-owner ./workspace   # use owner of a directory

# Generated variables (overridable via environment at run time):
#   UID, GID, WS_DIR, PACKAGE_NAME, UR_ROBOT_IP, USE_MOCK_HARDWARE, POLARIS_IP
# Example overrides:
#   WS_DIR=/custom_ws UR_ROBOT_IP=10.0.0.5 ./gen-dotenv.sh

set -euo pipefail

# Resolve project root (directory containing this script).
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"

USE_DIR_OWNER=0
DIR_PATH=""
if [[ "${1:-}" == "--from-dir-owner" ]]; then
  USE_DIR_OWNER=1
  DIR_PATH="${2:-}"
  if [[ -z "${DIR_PATH}" ]]; then
    echo "Error: missing directory after --from-dir-owner" >&2
    exit 1
  fi
fi

uid=""
gid=""

if [[ "${USE_DIR_OWNER}" -eq 1 ]]; then
  # Try GNU stat (-c) first, then BSD/macOS stat (-f).
  if stat -c '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -c '%u' "$DIR_PATH")"
    gid="$(stat -c '%g' "$DIR_PATH")"
  elif stat -f '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -f '%u' "$DIR_PATH")"
    gid="$(stat -f '%g' "$DIR_PATH")"
  else
    echo "Error: cannot determine owner of '$DIR_PATH' with stat." >&2
    exit 1
  fi
else
  # Current host user's ids.
  uid="$(id -u)"
  gid="$(id -g)"
fi

# Before writing the .env file, confirm overwrite if it already exists

# If .env exists, confirm overwrite; otherwise, proceed to create a new one.
if [[ -e "${ENV_FILE}" ]]; then
  echo "Warning: ${ENV_FILE} already exists." >&2
  # Only prompt if running interactively (stdin and stdout are terminals)
  if [[ -t 0 && -t 1 ]]; then
    if ! IFS= read -r -p "Overwrite it? [y/N]: " reply; then
      echo "No input received. Aborting to avoid overwriting." >&2
      exit 1
    fi
  else
    echo "Non-interactive shell detected. Aborting to avoid overwriting." >&2
    exit 1
  fi
  case "${reply:-}" in
    [yY]|[yY][eE][sS]) ;;
    *) echo "Aborted. Existing ${ENV_FILE} left unchanged."; exit 0 ;;
  esac
else
  echo "No existing .env found; a new one will be created at ${ENV_FILE}."
fi

# Write the .env file (overwrites if it exists)
{
  echo "# Autogenerated by gen-dotenv.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "UID=${uid}"
  echo "GID=${gid}"
  # Allow environment to override defaults at generation time
  echo "WS_DIR=${WS_DIR:-/ani_ws}"
  echo "PACKAGE_NAME=${PACKAGE_NAME:-auto_needle_insertion}"
  echo "UR_ROBOT_IP=${UR_ROBOT_IP:-192.168.56.2}"
  echo "USE_MOCK_HARDWARE=${USE_MOCK_HARDWARE:-true}"
  echo "POLARIS_IP=${POLARIS_IP:-192.168.56.5}"
} > "${ENV_FILE}"

echo "Wrote ${ENV_FILE} with:"
echo "  UID=${uid}"
echo "  GID=${gid}"
echo "  WS_DIR=${WS_DIR:-/ani_ws}"
echo "  PACKAGE_NAME=${PACKAGE_NAME:-auto_needle_insertion}"
echo "  UR_ROBOT_IP=${UR_ROBOT_IP:-192.168.56.2}"
echo "  USE_MOCK_HARDWARE=${USE_MOCK_HARDWARE:-true}"
echo "  POLARIS_IP=${POLARIS_IP:-192.168.56.5}"
