#!/usr/bin/env bash
# Generate a .env for Docker Compose with host UID/GID and project variables.
# Interactive behavior: if .env exists, warn and prompt to confirm overwrite; otherwise create a new one.
# Usage:
#   ./gen-dotenv.sh                 # use current user's ids
#   ./gen-dotenv.sh --from-dir-owner .   # use owner of a directory
#
# Generated variables (overridable via environment at run time):
#   Group 1: UID, GID, DOCKER_GID, HOST_WS_DIR, HOST_ROSBAG_DIR, PACKAGE_NAME
#   Group 2: UR_ROBOT_IP, USE_MOCK_HARDWARE
#   Group 3: POLARIS_IP
#   Group 4: GSCAM_LATENCY, GSCAM_PROTOCOL, GSCAM_VIDEO_WIDTH, GSCAM_VIDEO_HEIGHT
#   Group 5: ATI_SENSOR_IP, ATI_SENSOR_TYPE, ATI_SAMPLING_RATE
#   Group 6: USB_VIDEO_DEVICE, USB_VIDEO_WIDTH, USB_VIDEO_HEIGHT, USB_VIDEO_FPS
#   Group 7: FRANKA_ROBOT_TYPE, FRANKA_ROBOT_IP, FRANKA_USE_FAKE_HARDWARE, FRANKA_LOAD_GRIPPER
#   Group 8: Robot preflight automation switches and endpoints
#
# Example overrides:
#   HOST_WS_DIR=/path/to/repo UR_ROBOT_IP=10.0.0.5 ATI_SENSOR_IP=10.0.0.10 ./gen-dotenv.sh

set -euo pipefail

detect_usb_grabber() {
  local hagibis_dev=""
  for dev in /dev/video*; do
    local name_file="/sys/class/video4linux/$(basename "$dev")/name"
    [[ -r "$name_file" ]] || continue
    local name
    name=$(<"$name_file")
    if [[ "$name" == *Hagibis* ]]; then
      hagibis_dev="$dev"
      break
    fi
  done
  if [[ -z "$hagibis_dev" ]]; then
    echo "Error: USB_grabber 'Hagibis' not found" >&2
    return 1
  fi
  printf '%s' "$hagibis_dev"
}

detect_docker_gid() {
  # Allow override: DOCKER_GID=984 ./gen-dotenv.sh
  if [[ -n "${DOCKER_GID:-}" ]]; then
    printf '%s' "${DOCKER_GID}"
    return 0
  fi

  local gid=""
  if command -v getent >/dev/null 2>&1; then
    # Format: group:password:GID:user(s)
    gid="$(getent group docker 2>/dev/null | cut -d: -f3 || true)"
  elif [[ -r /etc/group ]]; then
    gid="$(awk -F: '$1=="docker"{print $3}' /etc/group || true)"
  fi

  # Non-fatal: some hosts (e.g., macOS) may not have a docker group
  if [[ -z "$gid" ]]; then
    echo "Warning: could not determine docker group GID (group 'docker' not found). DOCKER_GID will be empty." >&2
  fi

  printf '%s' "$gid"
}

# Resolve project root (directory containing this script).
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"

USE_DIR_OWNER=0
DIR_PATH=""
if [[ "${1:-}" == "--from-dir-owner" ]]; then
  USE_DIR_OWNER=1
  DIR_PATH="${2:-}"
  if [[ -z "${DIR_PATH}" ]]; then
    echo "Error: missing directory after --from-dir-owner" >&2
    exit 1
  fi
fi

uid=""
gid=""

if [[ "${USE_DIR_OWNER}" -eq 1 ]]; then
  # Try GNU stat (-c) first, then BSD/macOS stat (-f).
  if stat -c '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -c '%u' "$DIR_PATH")"
    gid="$(stat -c '%g' "$DIR_PATH")"
  elif stat -f '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -f '%u' "$DIR_PATH")"
    gid="$(stat -f '%g' "$DIR_PATH")"
  else
    echo "Error: cannot determine owner of '$DIR_PATH' with stat." >&2
    exit 1
  fi
else
  # Current host user's ids.
  uid="$(id -u)"
  gid="$(id -g)"
fi

docker_gid="$(detect_docker_gid)"

# If .env exists, confirm overwrite; otherwise, proceed to create a new one.
if [[ -e "${ENV_FILE}" ]]; then
  echo "Warning: ${ENV_FILE} already exists." >&2
  # Only prompt if running interactively (stdin and stdout are terminals)
  if [[ -t 0 && -t 1 ]]; then
    if ! IFS= read -r -p "Overwrite it? [y/N]: " reply; then
      echo "No input received. Aborting to avoid overwriting." >&2
      exit 1
    fi
  else
    echo "Non-interactive shell detected. Aborting to avoid overwriting." >&2
    exit 1
  fi
  case "${reply:-}" in
    [yY]|[yY][eE][sS]) ;;
    *) echo "Aborted. Existing ${ENV_FILE} left unchanged."; exit 0 ;;
  esac
else
  echo "No existing .env found; a new one will be created at ${ENV_FILE}."
fi

if [[ -z "${USB_VIDEO_DEVICE:-}" ]]; then
  USB_VIDEO_DEVICE="$(detect_usb_grabber)"
  echo "Detected USB video grabber: ${USB_VIDEO_DEVICE}"
fi

# Write the .env file (overwrites if it exists)
{
  echo "# Autogenerated by gen-dotenv.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

  # Group 1: IDs and repo/workspace settings
  echo "UID=${uid}"
  echo "GID=${gid}"
  echo "DOCKER_GID=${docker_gid}"
  echo "HOST_WS_DIR=${HOST_WS_DIR:-${PWD}}"
  echo "HOST_ROSBAG_DIR=${HOST_ROSBAG_DIR:-/mnt/dataset/rosbag_recording}"
  echo "RUNTIME_WS_DIR=${RUNTIME_WS_DIR:-/ani_ws}"
  echo "PACKAGE_NAME=${PACKAGE_NAME:-auto_needle_insertion}"

  echo

  # Group 2: UR robot configuration
  echo "UR_ROBOT_IP=${UR_ROBOT_IP:-192.168.56.2}"
  echo "USE_MOCK_HARDWARE=${USE_MOCK_HARDWARE:-true}"

  echo

  # Group 3: Polaris tracker
  echo "POLARIS_IP=${POLARIS_IP:-192.168.56.5}"

  echo

  # Group 4: GSCAM configuration
  echo "GSCAM_LATENCY=${GSCAM_LATENCY:-20}"
  echo "GSCAM_PROTOCOL=${GSCAM_PROTOCOL:-udp}"
  echo "GSCAM_VIDEO_WIDTH=${GSCAM_VIDEO_WIDTH:-640}"
  echo "GSCAM_VIDEO_HEIGHT=${GSCAM_VIDEO_HEIGHT:-480}"
  echo "GSCAM_FRAME_ID=${GSCAM_FRAME_ID:-polaris_vt_camera}"
  echo "GSCAM_NAMESPACE=${GSCAM_NAMESPACE:-/polaris_camera}"

  echo

  # Group 5: ATI force/torque sensor
  echo "ATI_SENSOR_IP=${ATI_SENSOR_IP:-192.168.56.8}"
  echo "ATI_SENSOR_TYPE=${ATI_SENSOR_TYPE:-ati_axia}"
  echo "ATI_SAMPLING_RATE=${ATI_SAMPLING_RATE:-500}"
  echo "ATI_HARDWARE_BIASING=${ATI_HARDWARE_BIASING:-false}"

  echo

  # Group 6: USB video grabber
  echo "USB_VIDEO_DEVICE=${USB_VIDEO_DEVICE}"
  echo "USB_VIDEO_WIDTH=${USB_VIDEO_WIDTH:-1920}"
  echo "USB_VIDEO_HEIGHT=${USB_VIDEO_HEIGHT:-1080}"
  echo "USB_VIDEO_FPS=${USB_VIDEO_FPS:-30.0}"

  echo

  # Group 7: Franka driver
  echo "FRANKA_ROBOT_TYPE=${FRANKA_ROBOT_TYPE:-fr3}"
  echo "FRANKA_ROBOT_IP=${FRANKA_ROBOT_IP:-192.168.56.4}"
  echo "FRANKA_USE_FAKE_HARDWARE=${FRANKA_USE_FAKE_HARDWARE:-false}"
  echo "FRANKA_LOAD_GRIPPER=${FRANKA_LOAD_GRIPPER:-false}"

  echo

  # Group 8: Robot preflight automation
  echo "AUTO_ROBOT_PREFLIGHT=${AUTO_ROBOT_PREFLIGHT:-false}"
  echo "AUTO_UR_DASHBOARD=${AUTO_UR_DASHBOARD:-true}"
  echo "AUTO_FRANKA_DESK=${AUTO_FRANKA_DESK:-true}"

  # UR dashboard preflight
  echo "UR_DASHBOARD_PORT=${UR_DASHBOARD_PORT:-29999}"
  echo "UR_DASHBOARD_TIMEOUT_SEC=${UR_DASHBOARD_TIMEOUT_SEC:-3}"
  echo "UR_WAIT_RUNNING_SEC=${UR_WAIT_RUNNING_SEC:-90}"
  echo "UR_WAIT_PLAYING_SEC=${UR_WAIT_PLAYING_SEC:-90}"
  echo "UR_INSTALLATION_FILE=${UR_INSTALLATION_FILE:-}"
  echo "UR_EXTERNAL_CONTROL_PROGRAM=${UR_EXTERNAL_CONTROL_PROGRAM:-}"
  echo "UR_AUTO_POWER_ON=${UR_AUTO_POWER_ON:-true}"
  echo "UR_AUTO_BRAKE_RELEASE=${UR_AUTO_BRAKE_RELEASE:-true}"
  echo "UR_AUTO_PLAY=${UR_AUTO_PLAY:-true}"

  # Franka Desk preflight
  echo "FRANKA_DESK_BACKEND=${FRANKA_DESK_BACKEND:-api}"
  echo "FRANKA_DESK_TIMEOUT_SEC=${FRANKA_DESK_TIMEOUT_SEC:-8}"
  echo "FRANKA_WAIT_FCI_SEC=${FRANKA_WAIT_FCI_SEC:-60}"
  echo "FRANKA_DESK_TOKEN=${FRANKA_DESK_TOKEN:-}"
  echo "FRANKA_DESK_BASE_URL=${FRANKA_DESK_BASE_URL:-}"
  echo "FRANKA_DESK_UNLOCK_ENDPOINT=${FRANKA_DESK_UNLOCK_ENDPOINT:-/desk/api/joints/unlock}"
  echo "FRANKA_DESK_FCI_ON_ENDPOINT=${FRANKA_DESK_FCI_ON_ENDPOINT:-/desk/api/system/fci/enable}"
  echo "FRANKA_DESK_STATUS_ENDPOINT=${FRANKA_DESK_STATUS_ENDPOINT:-}"
  echo "FRANKA_DESK_STATUS_EXPECT_REGEX=${FRANKA_DESK_STATUS_EXPECT_REGEX:-active[[:space:]]*\"?[[:space:]]*:[[:space:]]*true|fci[[:space:]]*\"?[[:space:]]*:[[:space:]]*true}"
  echo "FRANKA_DESK_PLAYWRIGHT_CMD=${FRANKA_DESK_PLAYWRIGHT_CMD:-node scripts/franka_desk_playwright.mjs}"

} > "${ENV_FILE}"

echo "Wrote ${ENV_FILE} with:"
echo "  [Group 1] IDs (UID/GID/DOCKER_GID), directories, and package name"
echo "  [Group 2] UR robot configuration"
echo "  [Group 3] Polaris tracker"
echo "  [Group 4] GSCAM configuration"
echo "  [Group 5] ATI force/torque sensor"
echo "  [Group 6] USB video grabber"
echo "  [Group 7] Franka driver"
echo "  [Group 8] Robot preflight automation"
