#!/usr/bin/env bash
# Generate a .env for Docker Compose with host UID/GID.
# Usage:
#   ./gen-dotenv.sh                 # use current user's ids
#   ./gen-dotenv.sh --from-dir-owner ./workspace   # use owner of a directory

set -euo pipefail

# Resolve project root (directory containing this script).
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"

USE_DIR_OWNER=0
DIR_PATH=""
if [[ "${1:-}" == "--from-dir-owner" ]]; then
  USE_DIR_OWNER=1
  DIR_PATH="${2:-}"
  if [[ -z "${DIR_PATH}" ]]; then
    echo "Error: missing directory after --from-dir-owner" >&2
    exit 1
  fi
fi

uid=""
gid=""

if [[ "${USE_DIR_OWNER}" -eq 1 ]]; then
  # Try GNU stat (-c) first, then BSD/macOS stat (-f).
  if stat -c '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -c '%u' "$DIR_PATH")"
    gid="$(stat -c '%g' "$DIR_PATH")"
  elif stat -f '%u' "$DIR_PATH" >/dev/null 2>&1; then
    uid="$(stat -f '%u' "$DIR_PATH")"
    gid="$(stat -f '%g' "$DIR_PATH")"
  else
    echo "Error: cannot determine owner of '$DIR_PATH' with stat." >&2
    exit 1
  fi
else
  # Current host user's ids.
  uid="$(id -u)"
  gid="$(id -g)"
fi

tmp="${ENV_FILE}.tmp"
{
  echo "# Autogenerated on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Used by Docker Compose for variable interpolation; not exported to containers."
  echo "UID=${uid}"
  echo "GID=${gid}"
  echo "WS_DIR=/ani_ws"
} > "${tmp}"

mv "${tmp}" "${ENV_FILE}"
echo "Wrote ${ENV_FILE} with UID=${uid} GID=${gid}"