services:
  zed_ros2_neural:
    image: zed_ros2_desktop_u24.04_sdk_5.1.0_cuda_12.6.3:latest
    container_name: zed_ros2_neural_jazzy
    privileged: true
    network_mode: host
    ipc: host
    pid: host

    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /dev/shm:/dev/shm
      - ./bridge.yaml:/bridge.yaml:ro
      - ./:/work:rw

    gpus: all

    stdin_open: true
    tty: true
    restart: "no"

    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /root/ros2_ws/install/local_setup.bash &&
        ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2 depth_quality:=NEURAL
      "

  rosbag_control_service:
    image: zed_ros2_desktop_u24.04_sdk_5.1.0_cuda_12.6.3:latest
    container_name: rosbag_control_service_jazzy
    user: "${uid:-1001}:${gid:-1001}"
    group_add:
      - "${docker_gid:-999}"
#    privileged: true
    network_mode: host
    ipc: host
    pid: host

    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - WORK_DIR=/work

    volumes:
      - ./rosbag_control_service.py:/opt/rosbag_control/rosbag_control_service.py:ro
      - ./run_openh_rosbag_record.sh:/opt/rosbag_control/run_openh_rosbag_record.sh:ro
      - ./:/work:rw
      - /mnt/dataset:/work/rosbag_recording:rw

    restart: unless-stopped

    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        python3 /work/rosbag_control_service.py
      "